### ISSUE TITLE
FIL-ETH integrations 

### ISSUE THREAD

**Issue by amiller68** [banyancomputer/estuary#3]
Right now Estuary relies on a local Lotus client for making deals on the FileCoin network. This is great if we just want to curate deals over FileCoin, but maybe we also want to integrate ETH and FIL ecosystems through implementing a general Client manager that is able to configure deals on whatever chain a user or node runner wants.

Opening up this thread to explore and log development on this issue.

**Comment by amiller68** [comment]
Direction: Make ETH deals as normal through the front end, but back up User's files left in staging to the FileCoin network. 
To be decided: When and how Files get batched together once Users submit deals to chain.

**Comment by ita-c** [comment]
@amiller68 can this be closed?

**Comment by amiller68** [comment]
Yes. This is becoming stale since we're just planning on using Claudia's datacap for backing up to FIL, and that's p much implemented.
