### ISSUE TITLE
Deal Configuration

### ISSUE THREAD

**Issue by amiller68** [banyancomputer/estuary#4]
@en0ma implemented Deal Configuration for Estuary, which we might need to do for configuring batching files together and providing intermediate staging. I am putting this here as a reminder to rebase when their PR is merged: https://github.com/application-research/estuary/pull/370

**Comment by amiller68** [comment]
Direction: Users make deals on ETH for each file upload via the front-end. Uploads are then pinned on Estuary and Content records reference a dealID under which the upload is covered.

**Comment by amiller68** [comment]
Deal Configruation and setting defaults has been moved to `estuary-www`.

**Comment by amiller68** [comment]
I forgot, I need to add another route for staging files that already have a deal posted, as well as state management and error handling for pulling files based on a dealId

**Comment by ita-c** [comment]
@amiller68 can this be closed?

**Comment by amiller68** [comment]
Yes
